import './Loading.scss';

// can't be suspended, so we can't use useTranslation in this component
const Loading: React.FC = () => (
  <div className="pageloader is-active is-danger">
    <span className="title">
      <div>
        Please wait, loading...
        <br />
        Bitte warten, wird geladen...
        <br />
        Veuillez patienter, chargement...
        <br />
        Attendere, caricamento in corso...
        <br />
        Even geduld, laden...
        <br />
        Espere, cargando...
        <br />
        Aguarde, carregando...
        <br />
        Περιμένετε, φόρτωση ...
        <br />
        Proszę czekać, trwa ładowanie...
        <br />
        Prosím čekejte, načítám...
        <br />
        Pričekajte, učitava se...
        <br />
        Моля, изчакайте, зарежда се...
        <br />
        Please wait, loading...
      </div>
    </span>
  </div>
);

export default Loading;
